### ISSUE TITLE
Logging into Children of Ur

### ISSUE THREAD

**Issue by Ghia42** [ChildrenOfUr/cou-issues#2714]
When I click on the "login" tab on Children of Ur.com it takes me to a page that says "Internal Server Error" and it says: 
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at cgiadmin@yourhostingaccount.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request

And when I launch the game it comes up with the Ur and it syas: Hello but it doesn't finish loading the game.

**Comment by Ghiai** [comment]
Failed to load resource: the server responded with a status of 404 ()
main.dart.js:1239 Could not load image: https://childrenofur.com/assets/streetLayers/LDOU5PQU0FD21PF/middleground.png
main.dart.js:701 Uncaught CastError: Instance of 'minified:y': type 'minified:y' is not a subtype of type 'minified:fL'
    at Object.j (https://childrenofur.com/game/main.dart.js:484:3)
    at Object.Vn (https://childrenofur.com/game/main.dart.js:701:26)
    at Object.a7 (https://childrenofur.com/game/main.dart.js:709:3)
    at p6.$1 (https://childrenofur.com/game/main.dart.js:18862:13)
    at Fh.$1 (https://childrenofur.com/game/main.dart.js:14004:30)
    at UT (https://childrenofur.com/game/main.dart.js:563:17)
    at HTMLImageElement.<anonymous> (https://childrenofur.com/game/main.dart.js:572:51)
BG1.png:1 Failed to load resource: the server responded with a status of 404 ()
main.dart.js:1239 Could not load image: https://childrenofur.com/assets/streetLayers/LDOU5PQU0FD21PF/BG1.png
main.dart.js:701 Uncaught CastError: Instance of 'minified:y': type 'minified:y' is not a subtype of type 'minified:fL'
    at Object.j (https://childrenofur.com/game/main.dart.js:484:3)
    at Object.Vn (https://childrenofur.com/game/main.dart.js:701:26)
    at Object.a7 (https://childrenofur.com/game/main.dart.js:709:3)
    at p6.$1 (https://childrenofur.com/game/main.dart.js:18862:13)
    at Fh.$1 (https://childrenofur.com/game/main.dart.js:14004:30)
    at UT (https://childrenofur.com/game/main.dart.js:563:17)
    at HTMLImageElement.<anonymous> (https://childrenofur.com/game/main.dart.js:572:51)
SKY.png:1 Failed to load resource: the server responded with a status of 404 ()
main.dart.js:1239 Could not load image: https://childrenofur.com/assets/streetLayers/LDOU5PQU0FD21PF/SKY.png
main.dart.js:701 Uncaught CastError: Instance of 'minified:y': type 'minified:y' is not a subtype of type 'minified:fL'
    at Object.j (https://childrenofur.com/game/main.dart.js:484:3)
    at Object.Vn (https://childrenofur.com/game/main.dart.js:701:26)
    at Object.a7 (https://childrenofur.com/game/main.dart.js:709:3)
    at p6.$1 (https://childrenofur.com/game/main.dart.js:18862:13)
    at Fh.$1 (https://childrenofur.com/game/main.dart.js:14004:30)
    at UT (https://childrenofur.com/game/main.dart.js:563:17)
    at HTMLImageElement.<anonymous> (https://childrenofur.com/game/main.dart.js:572:51)

**Comment by Ghiai** [comment]
I have cleared cache,cookies,links,removed and then re-added FireFox. Checked updates for Browsers which are automatically updated on my puter. Used Chrome,Firefox,and incognito with no luck re-entering UR. My internet connection is healthy wifi. Posted in previous reply what shows up in red on my console. I don't know if that was helpful as I know nothing about coding. My sincere apologies for not being more of a Techie. If there is anything else I can try please let me know. TY.

**Comment by Ghiai** [comment]
This evening I opened a new account via yahoo mail on FireFox and that Avatar is in with a new but similar name. My original Avatar that functioned until my game updated still can't get in via the same exact browser.Only difference was my original Avatar is a gmail registered address.It makes no sense......Any ideas????

**Comment by Klikini** [comment]
The first error is a known issue that I will fix soon (the login system relied on the old forums, so I'm going to put it in the website itself).

The second log indicates a street that doesn't exist. Do you remember which street that was, by any chance?

**Comment by Ghiai** [comment]
I was trying new streets, May have been Stenina Jora,Joklin Seddin Polenta??  I was typing in letters to see where I could go and wrote down a few. Hopefully it's one of those. I was minning previously in LLMenski caverns (Sp).
@Klikini

**Comment by Klikini** [comment]
@Ghiai That's a manageable list, I'll investigate. And thank you for reminding me about the login page this morning, I just fixed it about 5 minutes ago :)

**Comment by Ghiai** [comment]
Andy, I think i discovered my issue as I am stuck in game again. I was
teleporting from the stone plaques on a dead end street somewhere by the
Ramsley Way area and my game stopped working yesterday. The street plaques
may be the issue since I was teleporting everywhere else with no problem
until I used a plaque again. Sorry for the inconvenience Andy.

**Comment by Klikini** [comment]
No worries, I have teleported you to Cebarkul.
— Andy C.
