### ISSUE TITLE
Stuck at loading screen

### ISSUE THREAD

**Issue by zog-glitch** [ChildrenOfUr/cou-issues#2939]
## Username: Zog

When I log in I get the spinning world with "Greetings, Zog" but it never progresses beyond that. An alt user on the same browser works fine so I think it may be something broken with my profile or my location.

User-Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36`

## Zog's Log from Browser Console
```
main.dart.js:1 [Server Communication] Map data loaded. 0:00:00
main.dart.js:1 [SoundManager] Starting up... 0:00:01
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
game.childrenofur.com/:1 Access to XMLHttpRequest at 'https://childrenofur.com/feed/' from origin 'https://game.childrenofur.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
childrenofur.com/feed/:1 
       Failed to load resource: net::ERR_FAILED
main.dart.js:1 [SoundManager] Registered services 0:00:01
auth.esm.js:59 Cross-Origin-Opener-Policy policy would block the window.closed call.
(anonymous) @ auth.esm.js:59
auth.esm.js:59 Cross-Origin-Opener-Policy policy would block the window.closed call.
(anonymous) @ auth.esm.js:59
auth.esm.js:59 Cross-Origin-Opener-Policy policy would block the window.closed call.
(anonymous) @ auth.esm.js:59
auth.esm.js:59 Cross-Origin-Opener-Policy policy would block the window.closed call.
(anonymous) @ auth.esm.js:59
auth.esm.js:59 Cross-Origin-Opener-Policy policy would block the window.closed call.
(anonymous) @ auth.esm.js:59
auth.esm.js:59 Cross-Origin-Opener-Policy policy would block the window.closed call.
(anonymous) @ auth.esm.js:59
auth.esm.js:55 Cross-Origin-Opener-Policy policy would block the window.close call.
Gn @ auth.esm.js:55
auth.esm.js:55 Cross-Origin-Opener-Policy policy would block the window.close call.
Gn @ auth.esm.js:55
main.dart.js:1 user logged in with google: [REDACTED]
main.dart.js:1 [AuthManager] Setting API tokens 0:01:00
main.dart.js:1 [AuthManager] Logged in 0:01:00
main.dart.js:1 [StreetService] Requesting street "GA9S5T1LA0D27NG"... 0:01:00
main.dart.js:1 [StreetService] "GA9S5T1LA0D27NG" loaded. 0:01:00
main.dart.js:1 [StreetService] Assembling Street... 0:01:00
main.dart.js:1 Could not load image: https://childrenofur.com/assets/streetLayers/LA9S5T1LA0D27NG/middleplus.png
main.dart.js:1 Uncaught Error: CastError: Instance of 'minified:y': type 'minified:y' is not a subtype of type 'minified:fK'
    at Object.k (main.dart.js:1:16794)
    at Object.VS (main.dart.js:1:25138)
    at Object.V (main.dart.js:1:25408)
    at p_.$1 (main.dart.js:1:476437)
    at Fx.$1 (main.dart.js:1:361124)
    at Vi (main.dart.js:1:19916)
    at HTMLImageElement.<anonymous> (main.dart.js:1:20200)
main.dart.js:1 Uncaught TypeError: Cannot read properties of null (reading 'geL')
    at Jp.$1 (main.dart.js:1:794264)
    at Fx.$1 (main.dart.js:1:361124)
    at Vi (main.dart.js:1:19916)
    at main.dart.js:1:20200
main.dart.js:1 Could not load image: https://childrenofur.com/assets/streetLayers/LA9S5T1LA0D27NG/bg_2.png
main.dart.js:1 Uncaught Error: CastError: Instance of 'minified:y': type 'minified:y' is not a subtype of type 'minified:fK'
    at Object.k (main.dart.js:1:16794)
    at Object.VS (main.dart.js:1:25138)
    at Object.V (main.dart.js:1:25408)
    at p_.$1 (main.dart.js:1:476437)
    at Fx.$1 (main.dart.js:1:361124)
    at Vi (main.dart.js:1:19916)
    at HTMLImageElement.<anonymous> (main.dart.js:1:20200)
main.dart.js:1 Uncaught TypeError: Cannot read properties of null (reading 'geL')
    at Jp.$1 (main.dart.js:1:794264)
    at Fx.$1 (main.dart.js:1:361124)
    at Vi (main.dart.js:1:19916)
    at main.dart.js:1:20200
main.dart.js:1 Could not load image: https://childrenofur.com/assets/streetLayers/LA9S5T1LA0D27NG/middleground.png
main.dart.js:1 Uncaught Error: CastError: Instance of 'minified:y': type 'minified:y' is not a subtype of type 'minified:fK'
    at Object.k (main.dart.js:1:16794)
    at Object.VS (main.dart.js:1:25138)
    at Object.V (main.dart.js:1:25408)
    at p_.$1 (main.dart.js:1:476437)
    at Fx.$1 (main.dart.js:1:361124)
    at Vi (main.dart.js:1:19916)
    at HTMLImageElement.<anonymous> (main.dart.js:1:20200)
main.dart.js:1 Uncaught TypeError: Cannot read properties of null (reading 'geL')
    at Jp.$1 (main.dart.js:1:794264)
    at Fx.$1 (main.dart.js:1:361124)
    at Vi (main.dart.js:1:19916)
    at main.dart.js:1:20200
main.dart.js:1 Could not load image: https://childrenofur.com/assets/streetLayers/LA9S5T1LA0D27NG/foreground.png
main.dart.js:1 Uncaught Error: CastError: Instance of 'minified:y': type 'minified:y' is not a subtype of type 'minified:fK'
    at Object.k (main.dart.js:1:16794)
    at Object.VS (main.dart.js:1:25138)
    at Object.V (main.dart.js:1:25408)
    at p_.$1 (main.dart.js:1:476437)
    at Fx.$1 (main.dart.js:1:361124)
    at Vi (main.dart.js:1:19916)
    at HTMLImageElement.<anonymous> (main.dart.js:1:20200)
main.dart.js:1 Uncaught TypeError: Cannot read properties of null (reading 'geL')
    at Jp.$1 (main.dart.js:1:794264)
    at Fx.$1 (main.dart.js:1:361124)
    at Vi (main.dart.js:1:19916)
    at main.dart.js:1:20200
main.dart.js:1 Could not load image: https://childrenofur.com/assets/streetLayers/LA9S5T1LA0D27NG/sky.png
main.dart.js:1 Uncaught Error: CastError: Instance of 'minified:y': type 'minified:y' is not a subtype of type 'minified:fK'
    at Object.k (main.dart.js:1:16794)
    at Object.VS (main.dart.js:1:25138)
    at Object.V (main.dart.js:1:25408)
    at p_.$1 (main.dart.js:1:476437)
    at Fx.$1 (main.dart.js:1:361124)
    at Vi (main.dart.js:1:19916)
    at HTMLImageElement.<anonymous> (main.dart.js:1:20200)
main.dart.js:1 Uncaught TypeError: Cannot read properties of null (reading 'geL')
    at Jp.$1 (main.dart.js:1:794264)
    at Fx.$1 (main.dart.js:1:361124)
    at Vi (main.dart.js:1:19916)
    at main.dart.js:1:20200
main.dart.js:1 Could not load image: https://childrenofur.com/assets/streetLayers/LA9S5T1LA0D27NG/bg_1.png
main.dart.js:1 Uncaught Error: CastError: Instance of 'minified:y': type 'minified:y' is not a subtype of type 'minified:fK'
    at Object.k (main.dart.js:1:16794)
    at Object.VS (main.dart.js:1:25138)
    at Object.V (main.dart.js:1:25408)
    at p_.$1 (main.dart.js:1:476437)
    at Fx.$1 (main.dart.js:1:361124)
    at Vi (main.dart.js:1:19916)
    at HTMLImageElement.<anonymous> (main.dart.js:1:20200)
main.dart.js:1 Uncaught TypeError: Cannot read properties of null (reading 'geL')
    at Jp.$1 (main.dart.js:1:794264)
    at Fx.$1 (main.dart.js:1:361124)
    at Vi (main.dart.js:1:19916)
    at main.dart.js:1:20200
api.soundcloud.com/tracks/145012987.json?client_id=7d2a07867f8a3d47d4f059b600b250b1:1 
       Failed to load resource: the server responded with a status of 401 (Unauthorized)
main.dart.js:1 Uncaught Error: Instance of 'minified:cR'
    at Object.k (main.dart.js:1:16794)
    at Hu.$0 (main.dart.js:1:285334)
    at Object.TT (main.dart.js:1:55730)
    at Bb.U4 (main.dart.js:1:55765)
    at EX.$1 (main.dart.js:1:258946)
    at Vi (main.dart.js:1:19916)
    at MutationObserver.<anonymous> (main.dart.js:1:20200)
main.dart.js:1 Uncaught TypeError: Cannot read properties of null (reading 'geL')
    at Jp.$1 (main.dart.js:1:794264)
    at Fx.$1 (main.dart.js:1:361124)
    at Vi (main.dart.js:1:19916)
    at main.dart.js:1:20200
game.childrenofur.com/:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
```

**Comment by RobertBlackhart** [comment]
@zog-glitch 

We've seen that from some folks. If you are adventurous, you can try the dev version at https://game-dev.childrenofur.com. This is a rewritten version of the game client including the login screen widget.
